# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoostcampRelay23' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

post_install do |installer|
   installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         config.build_settings['SWIFT_VERSION'] = '3.0'
      end
   end
end

  # Pods for BoostcampRelay23

  target 'BoostcampRelay23Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoostcampRelay23UITests' do
    # Pods for testing
  end

end
